[simulation]
num_workers = 1
num_events = 10_000
detector_name = "detector"
sources = ["anode_Bi207"]
random_seed = 42

[detector]
num_channels = 300
channel_start_pos = 4.79
channel_widths = [2.395]
channel_spacing = 4.79
channel_increment_dir = "x"
threshold = 0.30
drift_velocity = 1.6
collection_efficiency = 0.80
electron_lifetime_ms = 10
signal_width = 58
channel_resolution_mev = 0.0236

[detector.geometry]
type = "rectangular_prism"
height = 3500
origin = [0, 0, 0]
face_size = [1437, 1000]

[anode_Bi207]
decay_rate = 37_000
daughter_shell_to_binding_energy = {K = 0.088, L = 0.01586, M = 0.003851}

[anode_Bi207.geometry]
type = "cylinder"
radius = 2.5
height = 0
origin = [973,115,3410]

[[anode_Bi207.decay_branches]]
probability = 0.0690
emissions = [
	{type = "photon", energy_mev = 1.770238, interaction_dist = 167, internal_conversion_coefficients = {K = 0.00345, L = 0.00049, M = 0.00013}},
	{type = "photon", energy_mev = 0.569698, interaction_dist = 96, internal_conversion_coefficients = {K = 0.01539, L = 0.00442, M = 0.00146}}
]

[[anode_Bi207.decay_branches]]
probability = 0.00131
emissions = [
	{type = "photon", energy_mev = 1.4422, interaction_dist = 150, internal_conversion_coefficients = {K = 0.00243, L = 0.00042, M = 0.00051}},
	{type = "photon", energy_mev = 0.89779, interaction_dist = 119, internal_conversion_coefficients = {K = 0.01779, L = 0.00498}}
]

[[anode_Bi207.decay_branches]]
probability = 0.0000092
emissions = [
	{type = "photon", energy_mev = 1.4422, interaction_dist = 150, internal_conversion_coefficients = {K = 0.00243, L = 0.00042, M = 0.00051}},
	{type = "photon", energy_mev = 0.32810, interaction_dist = 75, internal_conversion_coefficients = {K = 0.25}},
	{type = "photon", energy_mev = 0.569698, interaction_dist = 97, internal_conversion_coefficients = {K = 0.01539, L = 0.00442, M = 0.00146}}
]

[[anode_Bi207.decay_branches]]
probability = 0.84
emissions = [
	{type = "photon", energy_mev = 1.063656, interaction_dist = 129, internal_conversion_coefficients = {K = 0.08434, L = 0.02190, M = 0.00692}},
	{type = "photon", energy_mev = 0.569698, interaction_dist = 96, internal_conversion_coefficients = {K = 0.01539, L = 0.00442, M = 0.00146}}
]

[[anode_Bi207.decay_branches]]
probability = 0.089
emissions = [
	{type = "photon", energy_mev = 0.569698, interaction_dist = 96, internal_conversion_coefficients = {K = 0.01539, L = 0.00442, M = 0.00146}}
]
