[simulation]
num_workers = 28
num_events = 916_000
detector_name = "detector"
sources = ["anode_Bi207"]#, "far_source_A", "far_source_B"]
stat_divergence = "chi2"

[detector]
num_channels = 300
channel_start_pos = 4.79
channel_widths = [2.395]
channel_spacing = 4.79
channel_increment_dir = "x"
threshold = 0.30
drift_velocity = 1.6
fake_scale = 0.80#175
electron_lifetime_ms = 20.0
signal_width = 58
channel_resolution_mev = 0.0236

[detector.geometry]
type = "rectangular_prism"
height = 3500
origin = [0, 0, 0]
face_size = [1437, 1000]

[anode_Bi207]
decay_rate = 37_000
daughter_shell_to_binding_energy = {K = 0.088, L = 0.01586, M = 0.003851}

[anode_Bi207.geometry]
type = "cylinder"
radius = 2.5
height = 0
origin = [973,115,3410]

[[anode_Bi207.decay_branches]]
probability = 0.0690
emissions = [
	{type = "photon", energy_mev = 1.770238, interaction_dist = 168, internal_conversion_coefficients = {K = 0.00345, L = 0.00049, M = 0.00013}},
	{type = "photon", energy_mev = 0.569698, interaction_dist = 97, internal_conversion_coefficients = {K = 0.01539, L = 0.00442, M = 0.00146}}
]

[[anode_Bi207.decay_branches]]
probability = 0.00131
emissions = [
	{type = "photon", energy_mev = 1.4422, interaction_dist = 150, internal_conversion_coefficients = {K = 0.00243, L = 0.00042, M = 0.00051}},
	{type = "photon", energy_mev = 0.89779, interaction_dist = 119, internal_conversion_coefficients = {K = 0.01779, L = 0.00498}}
]

[[anode_Bi207.decay_branches]]
probability = 0.0000092
emissions = [
	{type = "photon", energy_mev = 1.4422, interaction_dist = 150, internal_conversion_coefficients = {K = 0.00243, L = 0.00042, M = 0.00051}},
	{type = "photon", energy_mev = 0.32810, interaction_dist = 78, internal_conversion_coefficients = {K = 0.25}},
	{type = "photon", energy_mev = 0.569698, interaction_dist = 97, internal_conversion_coefficients = {K = 0.01539, L = 0.00442, M = 0.00146}}
]

[[anode_Bi207.decay_branches]]
probability = 0.84
emissions = [
	{type = "photon", energy_mev = 1.063656, interaction_dist = 129, internal_conversion_coefficients = {K = 0.08431, L = 0.02190, M = 0.00695}},
	{type = "photon", energy_mev = 0.569698, interaction_dist = 97, internal_conversion_coefficients = {K = 0.01539, L = 0.00442, M = 0.00146}}
]

[[anode_Bi207.decay_branches]]
probability = 0.089
emissions = [
	{type = "photon", energy_mev = 0.569698, interaction_dist = 97, internal_conversion_coefficients = {K = 0.01539, L = 0.00442, M = 0.00146}}
]

[source_A]
decay_rate = 37_000

[source_A.geometry]
type = "cylinder"
radius = 2.5
height = 0
origin = [973,115,3410]

[[source_A.decay_branches]]
probability = 0.95628825 #0.9776
emission.type = "photon"
emission.energy_mev = 0.570
emission.interaction_dist = 8

# K-edge alternative of above
[[source_A.decay_branches]]
probability = 0.0153663
emission.type = "electron"
emission.energy_mev = 0.481

# L-edge alternative of above
[[source_A.decay_branches]]
probability = 0.0044183
emission.type = "electron"
emission.energy_mev = 0.554

# M-edge alternative of above
[[source_A.decay_branches]]
probability = 0.001456475
emission.type = "electron"
emission.energy_mev = 0.566

[source_B]
decay_rate = 37_000

[source_B.geometry]
type = "cylinder"
radius = 2.5
height = 0
origin = [973,115,3410]

[[source_B.decay_branches]]
probability = 0.64964
emission.type = "photon"
emission.energy_mev = 1.064
emission.interaction_dist = 12

# K-edge alternative of above
[[source_B.decay_branches]]
probability = 0.0708495
emission.type = "electron"
emission.energy_mev = 0.976

# L-edge alternative of above
[[source_B.decay_branches]]
probability = 0.0184015
emission.type = "electron"
emission.energy_mev = 1.049

# M-edge alternative of above
[[source_B.decay_branches]]
probability = 0.0078225
emission.type = "electron"
emission.energy_mev = 1.060

[[source_B.decay_branches]]
probability = 0.06841833
emission.type = "photon"
emission.energy_mev = 1.770
emission.interaction_dist = 16

# K-edge alternative of above
[[source_B.decay_branches]]
probability = 0.000237702
emission.type = "electron"
emission.energy_mev = 1.682

# L-edge alternative of above
[[source_B.decay_branches]]
probability = 0.000033663
emission.type = "electron"
emission.energy_mev = 1.754

# M-edge alternative of above
[[source_B.decay_branches]]
probability = 0.000008918
emission.type = "electron"
emission.energy_mev = 1.766

[[source_B.decay_branches]]
probability = 0.0013055853
emission.type = "photon"
emission.energy_mev = 1.442
emission.interaction_dist = 14

# K-edge alternative of above
[[source_B.decay_branches]]
probability = 0.0000031964
emission.type = "electron"
emission.energy_mev = 1.354

# L-edge alternative of above
[[source_B.decay_branches]]
probability = 0.0000005502
emission.type = "electron"
emission.energy_mev = 1.426

[far_source_A]
decay_rate = 37_000

[far_source_A.geometry]
type = "cylinder"
radius = 2.5
height = 0
origin = [921,105,0]#100.0, 115, 0]

[[far_source_A.decay_branches]]
probability = 0.0015
emission.type = "electron"
emission.energy_mev = 0.482

[[far_source_A.decay_branches]]
probability = 0.0044
emission.type = "electron"
emission.energy_mev = 0.556

[[far_source_A.decay_branches]]
probability = 0.0152
emission.type = "electron"
emission.energy_mev = 0.566

[[far_source_A.decay_branches]]
probability = 0.9776
emission.type = "photon"
emission.energy_mev = 0.570
emission.interaction_dist = 80

[far_source_B]
decay_rate = 37_000

[far_source_B.geometry]
type = "cylinder"
radius = 2.5
height = 0
origin = [921,105,0]

[[far_source_B.decay_branches]]
probability = 0.0054
emission.type = "electron"
emission.energy_mev = 1.060

[[far_source_B.decay_branches]]
probability = 0.0184
emission.type = "electron"
emission.energy_mev = 1.049

[[far_source_B.decay_branches]]
probability = 0.0703
emission.type = "electron"
emission.energy_mev = 0.976

[[far_source_B.decay_branches]]
probability = 0.7458
emission.type = "photon"
emission.energy_mev = 1.064
emission.interaction_dist = 120

[[far_source_B.decay_branches]]
probability = 0.0687
emission.type = "photon"
emission.energy_mev = 1.770
emission.interaction_dist = 160

[[far_source_B.decay_branches]]
probability = 0.0002
emission.type = "electron"
emission.energy_mev = 1.682

[[far_source_B.decay_branches]]
probability = 0.0912
emission.type = "photon"
emission.energy_mev = 1.440
emission.interaction_dist = 140

