[source]
decay_rate = 3000

[source.geometry]
type = "cylinder"
radius = 2
height = 0
origin = [0, 0, 0]

[[source.decay_branches]]
probability = 0.1
emissions = [
	{type = "electron", energy_mev = 1.2, interaction_dist = 0},
]

[[source.decay_branches]]
probability = 0.9
emissions = [
	{type = "photon", energy_mev = 2.4, interaction_dist = 240},
]
