[simulation]
num_workers = 1
num_events = 250_000
detector_name = "detector_long"
sources = ["Bi207"]
random_seed = 42

[detector_long]
num_channels = 2
channel_start_pos = 0.75
channel_widths = [0.75, 0.75]
channel_spacing = 1.5
channel_increment_dir = "r"
threshold = 0.26
drift_velocity = 1.5
electron_lifetime_ms = 3
channel_resolution_mev = 0.08
signal_width = 12

[detector_short]
num_channels = 2
channel_start_pos = 0.75
channel_widths = [0.75, 0.75]
channel_spacing = 1.5
channel_increment_dir = "r"
threshold = 0.26
drift_velocity = 1.5
electron_lifetime_ms = 3
channel_resolution_mev = 0.08
signal_width = 12

[detector_long.geometry]
type = "cylinder"
radius = 30
height = 205
origin = [0, 0, 0]

[detector_short.geometry]
type = "cylinder"
radius = 30
height = 45
origin = [0, 0, 0]

[Bi207]
decay_rate = 3000
daughter_shell_to_binding_energy = {K = 0.088, L = 0.01586, M = 0.003851}

[anode_Bi207.geometry]
type = "cylinder"
radius = 2.5
height = 0
origin = [0, 0, 0]

[[Bi207.decay_branches]]
probability = 0.0690
emissions = [
	{type = "photon", energy_mev = 1.770238, interaction_dist = 168, internal_conversion_coefficients = {K = 0.00345, L = 0.00049, M = 0.00013}},
	{type = "photon", energy_mev = 0.569698, interaction_dist = 97, internal_conversion_coefficients = {K = 0.01539, L = 0.00442, M = 0.00146}}
]

[[Bi207.decay_branches]]
probability = 0.00131
emissions = [
	{type = "photon", energy_mev = 1.4422, interaction_dist = 150, internal_conversion_coefficients = {K = 0.00243, L = 0.00042, M = 0.00051}},
	{type = "photon", energy_mev = 0.89779, interaction_dist = 119, internal_conversion_coefficients = {K = 0.01779, L = 0.00498}}
]

[[Bi207.decay_branches]]
probability = 0.0000092
emissions = [
	{type = "photon", energy_mev = 1.4422, interaction_dist = 150, internal_conversion_coefficients = {K = 0.00243, L = 0.00042, M = 0.00051}},
	{type = "photon", energy_mev = 0.32810, interaction_dist = 78, internal_conversion_coefficients = {K = 0.25}},
	{type = "photon", energy_mev = 0.569698, interaction_dist = 97, internal_conversion_coefficients = {K = 0.01539, L = 0.00442, M = 0.00146}}
]

[[Bi207.decay_branches]]
probability = 0.84
emissions = [
	{type = "photon", energy_mev = 1.063656, interaction_dist = 129, internal_conversion_coefficients = {K = 0.08431, L = 0.02190, M = 0.00695}},
	{type = "photon", energy_mev = 0.569698, interaction_dist = 97, internal_conversion_coefficients = {K = 0.01539, L = 0.00442, M = 0.00146}}
]

[[Bi207.decay_branches]]
probability = 0.089
emissions = [
	{type = "photon", energy_mev = 0.569698, interaction_dist = 97, internal_conversion_coefficients = {K = 0.01539, L = 0.00442, M = 0.00146}}
]
